addSbtPlugin("com.eed3si9n"         % "sbt-buildinfo"       % "0.9.0")
addSbtPlugin("com.typesafe.sbt"     % "sbt-native-packager" % "1.3.2")
addSbtPlugin("io.spray"             % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.geirsson"         % "sbt-scalafmt"        % "1.5.1")
addSbtPlugin("org.lyranthe.sbt"     % "partial-unification" % "1.1.0")
